apiVersion: v1
kind: Service

metadata:
  name: health-backend-service

spec:
  selector:
    app: health-backend

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500

  type: NodePort